### 10. Mostrar el largo promedio de las reviews por tipo de sentimiento ⭐

In [1]:
import pandas as pd

In [8]:
reviews = pd.read_csv('googleplaystore_user_reviews.csv')
reviews

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
...,...,...,...,...,...
64290,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64291,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64292,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64293,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64294,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN

Voy a limpiar las reviews con NaN en la columna "Translated_Review"

In [9]:
reviews.dropna(subset='Translated_Review', inplace=True)

In [16]:
reviews['largo_review'] = reviews.Translated_Review.map(lambda x: len(x))
reviews = reviews[['Sentiment', 'largo_review']]
reviews.groupby('Sentiment').mean()

           largo_review
Sentiment
Negative     136.843671
Neutral       51.849166
Positive     118.256105